language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t devenkapoor/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devenkapoor/docker-react npm run test